[Settings]
    ID = "g.erma.in"

[build]
    command = "gatsby build"

[context.production]
    publish = "public/"

[[redirects]]
    from = "https://nervous-goldwasser-43ceb1.netlify.com/*"
    to = "https://g.erma.in/:splat"
    status = 301